version: '3.8'
services:
  web:
    image: portfolio_web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_web
    ports:
      - "2320:80"
    restart: unless-stopped
